config:
  credentials: []
  project_repos:
    git.scc.kit.edu/m-team/flaat:
      branch: master
      repo: https://git.scc.kit.edu/m-team/flaat
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/m-team/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-dandelion-butterfly.sh
        container: qc.acc_paltry-charcoal-zebu
  QC.Doc:
    repos:
      git.scc.kit.edu/m-team/flaat find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-sangria-lemming.sh
        container: qc.doc_goopy-aquamarine-squirt
      git.scc.kit.edu/m-team/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-eggplant-squid.sh
        container: qc.doc_shaky-silver-spitz
      git.scc.kit.edu/m-team/flaat markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-white-stingray.sh
        container: qc.doc_blurry-xanthic-malamute
      git.scc.kit.edu/m-team/flaat restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-eggplant-dragon.sh
        container: qc.doc_clammy-carmine-mayfly
  QC.Lic:
    repos:
      git.scc.kit.edu/m-team/flaat licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-rose-dragon.sh
        container: qc.lic_goopy-cyan-bulldog
  QC.Sec:
    repos:
      git.scc.kit.edu/m-team/flaat bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-champagne-gecko.sh
        container: qc.sec_scummy-fuchsia-wrasse
  QC.Sty:
    repos:
      git.scc.kit.edu/m-team/flaat flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-periwinkle-owl.sh
        container: qc.sty_skinny-goldenrod-bullfrog
  QC.Ver:
    repos:
      git.scc.kit.edu/m-team/flaat get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-tangerine-dachshund.sh
        container: qc.ver_snazzy-mustard-maltese
timeout: 1800
